{% set name = "mkdocs-git-authors-plugin" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 77f97c321e08a8757beb866293eb257070b11cd5a080976bc6696b249cbade4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - mkdocs >=1.0

test:
  imports:
    - mkdocs_git_authors_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timvink/mkdocs-git-authors-plugin
  summary: Mkdocs plugin to display git authors of a page
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
