{% set name = "mkdocs-git-authors-plugin" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-git-authors-plugin-{{ version }}.tar.gz
  sha256: 10dfc57fb10d5c3aceb0e5cdea199ac3a7588979f26484eba46d935dc1044c26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - mkdocs >=1.0

test:
  imports:
    - mkdocs_git_authors_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timvink/mkdocs-git-authors-plugin
  summary: Mkdocs plugin to display git authors of a page
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
