schema_version: 1

context:
  name: mkdocs-git-authors-plugin
  version: 0.9.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 180cc80ef78d553676b850fb783e13506d7eadd30b13a070aa085b2d9ad0607d

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - mkdocs >=1.0

tests:
  - python:
      imports:
        - mkdocs_git_authors_plugin
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Mkdocs plugin to display git authors of a page
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/timvink/mkdocs-git-authors-plugin

extra:
  recipe-maintainers:
    - pavelzw
